### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [coriolinus/accept-header#2]
I don't want to use a different crate registry other than crates.io and using a git dependency is out of my scope too. Unfortunately, the name has been taken by [a different crate](https://github.com/tyrchen/accept-header), which [does not implement the `Header` trait](https://github.com/tyrchen/accept-header/issues/1). Perhaps you could publish it under a different name?

**Comment by coriolinus** [comment]
The different crate is precisely why this is not currently published on crates.io. I'm not particularly interested in negotiating with the prior owner of the crate name to take it over, and I do not wish to support two different crate names for the same crate, which is just a nightmare. 

Can you explain in a bit more detail why a git dependency does not work for you?

**Comment by JohnTheCoolingFan** [comment]
Not using a git dependency is more of a personal choice for me, rather than something rational. Crates.io is a more organic way to use packages, in my opinion. Yes, you can pin a dependency to a specific commit or tag, but in my opinion it is still a worse option than using crates.io feature-wise.
If the original author wouldn't like to negotiate or somehow solve this name conflict, I'll use a git dep to simply have my server application be more robust and conform to the standards correctly.
Thank you for the response.

**Comment by coriolinus** [comment]
I think in this case the git dependency is your best option.
