### ISSUE TITLE
Don't depend on `mime` crate

### ISSUE THREAD

**Issue by maxcountryman** [coriolinus/accept-header#3]
It seems like `mime` is ["rotting"](https://github.com/hyperium/mime/issues/153) and it's unclear if this will change in the future. Meanwhile, alternatives like [`mediatype`](https://github.com/picoHz/mediatype) already exist. Perhaps this crate should proactively drop `mime` and build on more modern foundations.

**Comment by coriolinus** [comment]
I'd be happy to look at a pr implementing this change.

**Comment by maxcountryman** [comment]
It ultimately made more sense to implement this as [its own crate](https://github.com/maxcountryman/headers-accept).
